### ISSUE TITLE
Stor avdelning med 2 mötestider samma dag.

### ISSUE THREAD

**Issue by puggan** [martin-green/skojjt#23]
Med ändringarna från ba9e757, så ser det ut som att vår spåraravdelning, inte längre kan rapportera in som de gjort hitils.

Mötet är uppdelar i 2 delar, en mellan 18-19, och en mellan 19-20, hitils har de lagts in som 2 möten på samma dag, och rapporterats separat.

Lösningen på problemet är kanske inte kod-relaterat, utan kanske administrativt, en variant är ju att rapportera in alla barn på samma möte, men de ger ju fel tid för hälften av barnen,
ett annat alternativ är att de kanske ska ligga som 2 olika avdelningar i skojjt, eller kanske rent av 2 olika avdelningar i scoutnet.

Du som vet hur xml-filerna blir, kanske har lite feedback på vad som är lämpligast, så tar jag upp det med kåren.

![screenshot_20170127_081513](https://cloud.githubusercontent.com/assets/866668/22363187/c43f70ec-e468-11e6-9812-2b33c6ee8921.png)

**Comment by martin-green** [comment]
Enligt bidragsreglerna kan en person bara vara på ett möte om dagen. Men det är nog inget problem att ha flera möten på samma dag i xml filen. Hur kommunen hanterar det vet jag inte. Det borde fungera.Jag trodde att ni hade hittat en bugg med era dubbelmöten. Men det var tydligen en feature!Jag ändrar tillbaka igen.

-------- Originalmeddelande --------
Från: puggan <notifications@github.com> 
Datum: 2017-01-30  09:12  (GMT+01:00) 
Till: martin-green/skojjt <skojjt@noreply.github.com> 
Kopia: Subscribed <subscribed@noreply.github.com> 
Rubrik: [martin-green/skojjt] Stor avdelning med 2 mötestider samma dag. (#23) 

Med ändringarna från ba9e757, så ser det ut som att vår spåraravdelning, inte längre kan rapportera in som de gjort hitils.
Mötet är uppdelar i 2 delar, en mellan 18-19, och en mellan 19-20, hitils har de lagts in som 2 möten på samma dag, och rapporterats separat.
Lösningen på problemet är kanske inte kod-relaterat, utan kanske administrativt, en variant är ju att rapportera in alla barn på samma möte, men de ger ju fel tid för hälften av barnen,

ett annat alternativ är att de kanske ska ligga som 2 olika avdelningar i skojjt, eller kanske rent av 2 olika avdelningar i scoutnet.
Du som vet hur xml-filerna blir, kanske har lite feedback på vad som är lämpligast, så tar jag upp det med kåren.


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/martin-green/skojjt","title":"martin-green/skojjt","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/martin-green/skojjt"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Stor avdelning med 2 mötestider samma dag. (#23)"}],"action":{"name":"View Issue","url":"https://github.com/martin-green/skojjt/issues/23"}}}

**Comment by puggan** [comment]
Då kan de fortsätta som tidigare.

Buggen är väl att vi har för få ledare för att köra 2 avdelningar :-)
